# Generated by Django 3.0.3 on 2020-12-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0007_group_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
