# Generated by Django 3.0.3 on 2020-12-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0013_auto_20201205_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='letters',
        ),
        migrations.AddField(
            model_name='profile',
            name='letters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secret.Letter'),
        ),
    ]
