# Generated by Django 3.0.3 on 2020-12-06 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secret', '0015_auto_20201205_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='letters',
        ),
        migrations.AddField(
            model_name='letter',
            name='angel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letter',
            name='mortal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
