# Generated by Django 3.0.3 on 2020-12-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secret', '0016_auto_20201206_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='angel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='mortal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
