# Generated by Django 3.0.3 on 2020-12-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0006_auto_20201205_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
